### ISSUE TITLE
협업 관련 - storybook 제안해봅니다.

### ISSUE THREAD

**Issue by fridayCCC** [TaskWeaver/frontend_app#1]
## 요약
- 디자이너 협업 전달용으로 `storybook_flutter`을 제안합니다.

## 이유
- 웹에서는 storybook을 만들어 공유해서 디자이너가 만든 시안을 디자이너가 직접 확인해서 피드백을 받는 경우가 많습니다.
- flutter에도 비슷한 기능이 있는지 찾아보니 'storybook_fluttter'가 있더라구요.

**Comment by fridayCCC** [comment]
- [ ] storybook 사용 세팅 (dev에서만)
- [ ] storybook 배포 찾아보기
- [ ] storybook 작성 방법 문서화

**Comment by fridayCCC** [comment]
- [ ] wigetbook 적용하기

**Comment by fridayCCC** [comment]
widget book은 flutter, dart 버전 문제가 있음. 조금 더 찾아보아야  할 듯.

**Comment by jjoonleo** [comment]
혹시 정확히 어떤 문제가 있는지 공유해 주실 수 있으신가요?
