### ISSUE TITLE
DX 협업 관련 - 폴더 구조 제안

### ISSUE THREAD

**Issue by fridayCCC** [TaskWeaver/frontend_app#13]
## 요약
- 프로젝트 진행에 앞서 문서 구조를 간단히 제안해봅니다.

## 이유
- 일단 너무 복잡하고 구체적으로 구조를 제안하기 보다는 큰 틀을 정하고 세세한 부분은 추후 의논하는 것을 전제로 했습니다.

## 폴더 구조를 제안합니다.
   - `shared` 
       - 현재 프로젝트에 직접적으로 영향을 받지 않는다.
       - 타 라이브러리, 외부 종속성을 래핑하는 클래스입니다.
       - 2순위 테스트 대상

   - `core`
       - 현재 프로젝트의 비즈니스 로직과 연관있다.
       - model, repositories, service 등
       - 1순위 테스트 대상

  - `app`
      - shared 폴더 + core 폴더를 결합하여 실제 실행되는 최종 앱

   - `main` 
     - 실행 (live, stage, test, dev)

다음과 같은 모습으로 프로젝트가 구성될 것을 예상합니다.
 ex) 예시
```bash
assets 
  - fonts
  - html
  - i18n
  - images
  - icons
  - videos

lib
  - shared
     - uikit : 디자인된 widget
     - helper : 자주 사용되는 mixin
     - utils : 범용적으로 사용될 수 있는 함수, 클래스
     - wrapper : 타 라이브러리 wrapper
  - core
     - config : core 내에서 사용되는 config (통신 관련)
     - const : core 내에서 사용되는 constance
     - utils: core 내에서 사용되는 utils
     - [domain이름]
       - data : dto, repositories
       - domain : models
       - usecase : usecase
  - app
     - config : theme, routes 등 빌드 시점에 결정된 고정값
     - const : app 내에서 사용되는 constance
     - page
        - [page이름] : state, view, viewModel, screen
     
  - main // 
    - dev, test, stage, live에 따라 분기 처리 담당
```

- 모호한 부분, 그리고 더 나은 이름이 있는지 같이 찾아봅시다

**Comment by jjoonleo** [comment]
Layer-first 구조 보다는 Feature-first 구조가 더 낫지 않을까 제안해 봅니다. Feature-first로 구성해야 데이터의 흐름이 한 폴더안에서 이루어지고 현재 프로젝트가 많이 복잡하지 않기 때문에 이런식으로 구성하는 것이 폴더 구조를 보고 더 쉽게 프로젝트 구조를 파악할 수 있을 것이라 생각합니다

**Comment by fridayCCC** [comment]
저도 그 부분에 있어서 고민을 했습니다. 

1. feature 별로 관리를 했을 때,
```
> lib
  > app
    > feature
      > [feature name]
          > data
          > domain
          > ui 
      ...
    > shared  ------> shared across features
      > data
      > domain
      > ui 
  > core  -----> shared across the entire app
    > di (dependency injection)
    > navigation or routing
    > utils
    ...
```
- 하나의 기능을 빠르게 살펴볼 수 있다.
- `shared`의 기준을 잡기 모호할 수 있다.
- 프로젝트 크기가 커졌을 때 장점은 한 폴더 내에서 모든 것들을 찾아갈 수 있으니 파악이 빠르다.
- 새로운 기능이 기존 기능에 의존도가 있을 때, feature가 비대해 질 수 있다.

2. layer 별로 관리를 했을 때,
- 하나의 기능을 보기 위해 여러 폴더를 참고해야 한다.
- 데이터 흐름을 한눈에 파악하기 어렵다.
- 모듈화와 테스트가 용이하다.
- 전체 구조를 한눈에 파악하기 쉽다.


다음 고민 사항의 결론으로 저는 이렇게 생각했습니다.

<img src='https://miro.medium.com/v2/resize:fit:1400/format:webp/1*pDyNGV21ryWzZzMUdn0Sdg.png' />
 - domain, data 레이어 까지 묶어서 `core`폴더 내에서 `domain`단위로 관리하고, `app`폴더 밑에서는 페이지 단위로 조립해서 사용하자. 
 이유: 
   1. data 레이어까지 묶어 두었을 때, core 내에서 `data`에 대한 흐름을 파악하는 것에 문제가 없을 것으로 예상됨.
   2. `shared`, `core` 폴더 사용으로 재사용성을 최대한 높일 수 있음.
   3. `app`에서는 페이지 단위로 조립해서 사용하기 때문에 추후 feature가 겹치는 페이지가 기획되더라도 폴더 구조에 영향을 끼치지 않음.
      ex) 팀을 만든 유저가 팀 관리 페이지가 생긴다고 가정하면,
            `팀원 목록`,  `각 팀원이 현재 하고 있는 일 `,  `현재 팀에서 진행중인 테스크` 등을 한 눈에 보여줘야 하는 요구사항이 있다면,
            이 팀 summary 페이지는 팀원, 테스크 등 다양한 도메인에 걸쳐 있는 상황이 됨.
    4. 현재 기획 요구 사항이 많지 않으므로, 작은 프로젝트에서 Feature-first에 대한 메리트가 크게 없음.

**Comment by fridayCCC** [comment]
```
assets 
  - fonts
  - html
  - i18n
  - images
  - icons
  - videos

lib
  - shared
     - atom : 디자인된 widget
     - helper : 자주 사용되는 mixin
     - utils : 범용적으로 사용될 수 있는 함수, 클래스
     - wrapper : 타 라이브러리 wrapper
  - core
     - config : core 내에서 사용되는 config (통신 관련)
     - const : core 내에서 사용되는 constance
     - utils: core 내에서 사용되는 utils
     - [domain이름]
       - data : entity, repositories
       - domain : models, usecase
  - app
     - config : theme, routes 등 빌드 시점에 결정된 고정값
     - const : app 내에서 사용되는 constance
     - presentation
        - [page이름] : state, view, viewModel, screen
     
  - main // 
    - dev, test, stage, live에 따라 분기 처리 담당
```
