### ISSUE TITLE
i18n 적용하기

### ISSUE THREAD

**Issue by fridayCCC** [TaskWeaver/frontend_app#15]
## 요약
- 현재 구현한 페이지에 i18n을 적용해봅니다. 

## 마감 날짜
- ~1/11

- [x] i18n 관련 라이브러리를 살펴보고 하나를 정하면 하단에 코멘트를 달아주세요
- [ ] 현재 main에 구현된 페이지에 적용합니다.
- [ ] 공유가 필요하다고 생각되는 부분은 dartdoc으로 예시를 작성합니다.

**Comment by jjoonleo** [comment]
flutter_localization 라이브러리가 flutter가 공식적으로 소개하고 있는 라이브러리인 듯 합니다.
https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization


제공해 주는 예시 프로젝트입니다.
https://github.com/flutter/website/tree/main/examples/internationalization/gen_l10n_example

**Comment by brownglasses** [comment]
flutter Easy localization 을 적용하는 것도 좋을 것 같습니다 
https://pub.dev/packages/easy_localization  문법이 쉬워서 사용하기 편할 것 같습니다

제공해주는 예시 프로젝트입니다.
https://github.com/aissat/easy_localization/blob/develop/example/lib/main.dart

추가로 아래 글 보시면 사용법을 쉽게 알 수 있습니다.
https://blog.naver.com/chandong83/222422479689

**Comment by fridayCCC** [comment]
두 라이브러리 살펴보고 짧게 의견 남겨보겠습니다.

**Comment by fridayCCC** [comment]
두 라이브러리를 모두 살펴본 결과, 프로젝트에 최종적으로 `flutter easy localization`을 사용했으면 합니다.
- 사용이 단순함
- 지원을 위해 사용하는 라이브러리 필요 X
- code generation으로 휴먼 에러를 줄일 수 있음

**Comment by jjoonleo** [comment]
https://pub.dev/packages/slang
이 라이브러리도 좋은 것 같습니다
i18n을 flutter에서 지원하기 위해 개발되었다고 합니다
구글에서 지원하는 arb 파일 포맷을 사용할 수 있습니다
Code generator로 arb파일을 dart파일로 변환하는 것 같습니다
t.text 와 같은 형식으로 간단하게 사용할 수 있습니다

**Comment by fridayCCC** [comment]
slang 사용, arg 파일 사용

**Comment by jjoonleo** [comment]
혁진님께서 intl이야기도 해 주셔서 아래 링크에서 추천하는 방법도 고려해 보면 좋을 것 같습니다. arb파일을 바로 dart파일로 변환해 주는 ide extension이 있다고 합니다. 이를 이용하면 intl 기능과 arb파일의 장점을 모두 사용하며 context를 이용하는 복잡한 방법 없이 바로 Intl.message('appName') 이렇게 사용할 수 있다고 합니다.
https://jay-flow.medium.com/flutter-localizations-%EC%99%84%EC%A0%84-%EC%A0%95%EB%B3%B5-%ED%95%98%EA%B8%B0-8fa5f50a3fd2
