### ISSUE TITLE
DX 관련 - 린트 설정 제안 드립니다.

### ISSUE THREAD

**Issue by fridayCCC** [TaskWeaver/frontend_app#2]
## 요약
- `flutter_lints`, `import_sorter` 설정으로 린트 설정을 통일했으면합니다.

## 이유
- 린트 설정을 간략화 할 수 있고, import_sorter은 웹에서는 기본 린트설정에서 plugin으로 작성할 수 있는데, flutter에서는 보이지 않아 제안해봅니다. 
- 앱이 커질 때 파일에서 서로서로 import 해오는데, 이 때 순서를 통일해두면 파악이 더 쉽더라구요.

## 참고
https://deku.posstree.com/ko/flutter/linter/#flutter_lints

**Comment by brownglasses** [comment]
https://pub.dev/packages/import_sorter

**Comment by brownglasses** [comment]
flutter 자주 사용하는 lint:

linter:
  rules:
    - prefer_const_constructors
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - avoid_types_on_closure_parameters
    - avoid_annotating_with_dynamic
    - avoid_escaping_inner_quotes
    - avoid_function_literals_in_foreach_calls
    - avoid_private_typedef_functions
    - combinators_ordering
    - curly_braces_in_flow_control_structures
    - lowercase_with_underscores
    - omit_local_variable_types
    - annotate_overrides
    - sort_constructors_first
    - unawaited_futures
    - directives_ordering
    - unnecessary_final
    - unnecessary_parenthesis
    - conditional_uri_does_not_exist
    - prefer_single_quotes
    - await_only_futures
    - always_use_package_imports
    - avoid_empty_else
    - comment_references
    - prefer_void_to_null
    - use_key_in_widget_constructors
