### ISSUE TITLE
라우팅 패키지 관련 - go_router 사용을 제안드립니다.

### ISSUE THREAD

**Issue by jjoonleo** [TaskWeaver/frontend_app#26]
## 요약
아래 코드와 같이 url을 정의해서 navigation을 도와주는 패키지입니다.
```dart
GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
```

## 이유
이후 qr초대 혹은 link로 초대기능 구현 시 deep link가 필요할 수도 있을 것이라는 생각이 들었습니다.
또한 기본 navigator보다 subroute, error handling, transition등 기능과 사용성 측면에서 뛰어납니다.
flutter team에서 직접 제공하는 패키지입니다.

##관련 링크
https://docs.flutter.dev/ui/navigation/deep-linking
https://www.youtube.com/watch?v=b6Z885Z46cU
https://pub.dev/packages/go_router

**Comment by brownglasses** [comment]
사용감도 기존 navigation 보다 편하고 레퍼런스도 많아서 좋은 것 같습니다 .
