### ISSUE TITLE
intl 라이브러리 사용을 제안합니다 

### ISSUE THREAD

**Issue by brownglasses** [TaskWeaver/frontend_app#37]
## 요약
https://pub.dev/packages/intl
- 메시지 번역, 복수형 및 성별, 날짜/숫자 형식 지정 및 구문 분석, 양방향 텍스트를 포함한 국제화 및 현지화 기능을 제공합니다.
- 날짜 형식 변환을 위해 이 라이브러리를 사용하면 좋을 것 같습니다.
예시 )
```dart
Text(DateFormat('yyyy.MM.dd').format(endDate!)),
``` 

## 이유
- DateTime 객체의 형식을 수정해야 할 때 편하게 사용할 수 있습니다.

## 의논점
- 하지만 단지 DateTime 만을 다루기 위해 패키지를 추가하면 앱의 크기가 커질까 봐 우려됩니다.
- DateTime을 다루는 함수를 구현할 지 이 라이브러리를 사용할 지 의논하고 싶습니다.

**Comment by fridayCCC** [comment]
만약 intl을 date 타임을 다루기 위해서만 사용한다면 다음과 같이 date util 들을 만들어 사용하는 편이 나을 것 같습니다.  저번에 slang으로 다국어 지원을 결정하면서 intl에서 제공하는 기능들을 거의 안 쓰지 않을까 생각됩니다.

date utils 예시
```dart
String intlFormatDate(DateTime date) {
  String year = date.year.toString();
  String month = date.month.toString().padLeft(2, '0');
  String day = date.day.toString().padLeft(2, '0');

  return '$year-$month-$day';
}
```
