### ISSUE TITLE
 팀원들끼리 Dart SDK와 Flutter SDK의 버전을 일치시킬 필요가 있을 것 같습니다 

### ISSUE THREAD

**Issue by brownglasses** [TaskWeaver/frontend_app#5]
Dart SDK와 Flutter SDK의 버전을 일치시키는 것이 좋을 것 같습니다 . 동일한 개발 환경을 가지고 작업할 수 있으면 좋을 것 같습니다.

**Comment by fridayCCC** [comment]
- fvm - flutter stable 버전 사용
- fvm 간단 문서 작성
